---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mulazjre/cdn.mulat.org
    - mkdir -p $DEPLOYPATH/awash
    - /bin/cp MulatAwash-*.* $DEPLOYPATH/awash
    - /bin/cp README.md $DEPLOYPATH/awash
    - zip -j awash.zip $DEPLOYPATH/awash/*
    - mv awash.zip $DEPLOYPATH/awash
    - echo "....finished, awash ..........."

