---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mulazjre/cdn.mulat.org
    - kdir -p $DEPLOYPATH/awash
    - /bin/cp MulatAwash-*.* $DEPLOYPATH/awash
    - /bin/cp README.md $DEPLOYPATH/awash
    - zip -d awash.zip $DEPLOYPATH/awash 
    - ehco "....finished....."