---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mulazjre/cdn.mulat.org
    - /bin/mkdir -p $DEPLOYPATH/awash
    - /bin/cp MulatAwash-*.* $DEPLOYPATH/awash
    - /bin/cp README.md $DEPLOYPATH/awash
    - zip -d $DEPLOYPATH/awash/awash.zip ./awash 
    - ehco "....finished"